[package]
name = "circuits-halo2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_gadgets = "0.2"
halo2_proofs = "0.2"
group = "0.11"
ff = "0.11"
pasta_curves = "0.2.1"
